grayscale/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url('^$', TemplateView.as_view(template_name='index.html')),
)

holmes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^', include('grayscale.urls', namespace = 'grayscale')),
    url(r'^journal/', include('journal.urls', namespace = 'journal')),
    url(r'^admin/', include(admin.site.urls)),
    # Admin Views
    url(r'^orchestra/admin/',
        include(admin.site.urls)),

    # Registration Views
    # Eventually these will be auto-registered with the Orchestra URLs, but for
    # now we need to add them separately.
    url(r'^orchestra/accounts/',
        include('registration.backends.default.urls')),

# Logout then login is not available as a standard django
# registration route.
    url(r'^orchestra/accounts/logout_then_login/$',
        auth_views.logout_then_login,
        name='logout_then_login'),

    # Orchestra URLs
    url(r'^orchestra/',
        include('orchestra.urls', namespace='orchestra')),

# Beanstalk Dispatch URLs
    url(r'^beanstalk_dispatch/',
        include('beanstalk_dispatch.urls')),
]

journal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
   # ex: /polls/
    url(r'^$', views.index, name='main'),
    url(r'^entries/$', views.entryview, name='entryview'),
    url(r'^entries/addentry$', views.addentry, name='addentry'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^addquestion/$', views.addquestion, name='addquestion'),
    url(r'^(P<question_id>[0-9]+)/addchoice', views.addchoice, name='addchoice'),
]

grayscale/models.py
from django.db import models

# Create your models here.

journal/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
class Entry(models.Model):
    entry = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.entry
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

grayscale/views.py
from django.shortcuts import render

# Create your views here.

journal/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone
from .models import Choice, Question, Entry


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'main.html', context)
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        if(request.POST['nc'] != ''):
            nc = addchoice(request, question_id)
            return nc
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('journal:results', args=(p.id,)))
def addquestion(request):
    newquestion = request.POST['nq']
    nq = Question(question_text=newquestion,pub_date=timezone.now())
    nq.save()
    return HttpResponseRedirect(reverse('journal:index'))
def addchoice(request, q_id):
    q = get_object_or_404(Question, pk=q_id)
    newchoice = request.POST['nc']
    nc = Choice(choice_text=newchoice,votes=1,question_id=q_id)
    nc.save()
    return HttpResponseRedirect(reverse('journal:results', args=(q.id,)))
def entryview(request):
    latest_entry_list = Entry.objects.order_by('-pub_date')[:5]
    context = {'latest_entry_list': latest_entry_list}
    return render(request, 'entryview.html', context)
def addentry(request):
    newentry = request.POST['entry']
    ne = Entry(entry=newentry,pub_date=timezone.now())
    ne.save()
    return HttpResponseRedirect(reverse('journal:entryview'))

grayscale/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Holmes - Disease Research in the Cloud</title>

    <!-- Bootstrap Core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="static/css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                      Holmes
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Holmes</h1>
                        <p class="intro-text">A free, collaborative system to analyze disease data in the cloud.<br>Created by Alan Williams.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About holmes</h2>
                <p>This software was developed with the idea to study various orphan diseases and build a system by which to analyze them no matter where you are in the world.</p>
                <p>I plan to do this by building a computing system connected to AWS, a journal system served here, and by forming a partnership with a labratory somewhere in the world.</p>
                <p>We, of course, can not do this without users, so please, email me and let me know what you would like to do for your next project.</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Use Holmes</h2>
                    <p>You can currently use the poll app to choose what we do next.  Also, we take suggestions via email.</p>
                    <a href="journal/" class="btn btn-default btn-lg">Visit Poll Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Holmes Team</h2>
                <p>Feel free to email us to provide some feedback on our software, give us suggestions for new features, or to just say hello!</p>
                <p><a href="mailto:astropiloto@gmail.com">astropiloto@gmail.com</a>
                </p>
<!--                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
                -->
                
            </div>
        </div>
    </section>
    
    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Alan Williams 2015</p>
            <p><a href="https://www.codementor.io"><img width="108" src="//cdn.codementor.io/badges/built_with_codementor_dark@2x.png" alt="Codementor" /></a></p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="static/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="static/js/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="static/js/grayscale.js"></script>

</body>

</html>

journal/templates/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}" />
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'journal:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
Enter a new choice:
    <input type="text" name="nc"/>
<input type="submit" value="Vote" />
</form>

journal/templates/entryview.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}" />
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                      Home
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Poll</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/journal/entries">Journal</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br>
<br>
<hr>
{% if latest_entry_list %}
    <ul>
    {% for entry in latest_entry_list %}
        <li>{{ entry.entry }}</li>
    {% endfor %}
    </ul>
    <form action="{% url 'journal:addentry' %}" method="post">
{% csrf_token %}
    Enter a new entry:
    <TEXTAREA NAME="entry" ROWS=5 COLS=40 ></TEXTAREA>
<input type="submit" value="Add entry" />
</form>
{% else %}
    <p>No entries are available.</p>
     <form action="{% url 'journal:addentry' %}" method="post">
{% csrf_token %}
    Enter a new entry:
    <TEXTAREA NAME="entry" ROWS=5 COLS=40 ></TEXTAREA>
<input type="submit" value="Add entry" />
</form>
{% endif %}
<script src="{% static 'jquery.js'%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap.min.js'%}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'jquery.easing.min.js'%}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'grayscale.js'%}"></script>

journal/templates/main.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}" />
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                      Home
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Poll</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/journal/entries/">Journal</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br>
<br>
<hr>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/journal/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    <form action="{% url 'journal:addquestion' %}" method="post">
{% csrf_token %}
    Enter a new question:
    <input type="text" name="nq"/>
<input type="submit" value="Add question" />
</form>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<script src="{% static 'jquery.js'%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap.min.js'%}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'jquery.easing.min.js'%}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'grayscale.js'%}"></script>

journal/templates/results.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}" />
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'journal:detail' question.id %}">Vote again?</a>